name: Parasol MaaS
version: 1.0.0
schema: v1
models:
  - name: OpenAI GPT-5
    provider: openai
    model: gpt-5	
    apiKey: "${apitoken}"
  - name: Nomic Embeddings
    provider: openai
    model: "${nomic-embed-model}"
    apiBase: "${nomic-embed-endpoint}/v1/"
    maxBatchSize: 32
    apiKey: "${nomic-embed-token}"
    roles:
      - embed
