name: Parasol MaaS
version: 1.0.0
schema: v1
models:
  - name: OpenAI GPT-5
    provider: openai
    model: gpt-5	
    apiKey: "${apitoken}"
  - name: Nomic Embeddings
    provider: openai
    model: "${NOMIC_EMBED_MODEL}"
    apiBase: "${NOMIC_EMBED_ENDPOINT}/v1/"
    maxBatchSize: 32
    apiKey: "${NOMIC_EMBED_TOKEN}"
    roles:
      - embed
  - name: Granite 3.3 8b
    provider: openai
    model: "${GRANITE_3_3_8B_MODEL}"
    apiBase: "${GRANITE_3_3_8B_ENDPOINT}"
    apiKey: "${GRANITE_3_3_8B_TOKEN}"
    roles:
      - autocomplete
    requestOptions:
      extraBodyProperties:
        think: false # turning off the thinking
